# Global cache configuration
caches:
  - key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
  - key: android-sdk-34
    paths:
      - $CM_ANDROID_SDK_ROOT/platforms/android-34
      - $CM_ANDROID_SDK_ROOT/build-tools/34.0.0

workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    
    environment:
      groups:
        - android_signing
      vars:
        BUILD_TYPE: "release"
      java: 17

    triggering:
      events:
        - tag
      branch_patterns:  # Changed from branch-patterns to branch_patterns
        - pattern: main
          include: true

    scripts:
      - name: Set up Android SDK
        script: |
          # Using Codemagic's preconfigured environment
          export PATH=$PATH:$CM_ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$CM_ANDROID_SDK_ROOT/platform-tools
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Build and Verify
        script: |
          ./gradlew clean assemble${BUILD_TYPE}
          ./gradlew lintRelease
          apkanalyzer apk summary app/build/outputs/apk/release/app-release.apk
          apkanalyzer files list app/build/outputs/apk/release/app-release.apk | grep lib/arm64-v8a/

      - name: Security Check
        script: |
          if grep -r "android:debuggable=\"true\"" app/src/main/AndroidManifest.xml; then
            echo "ERROR: Release build must not be debuggable!"
            exit 1
          fi

    artifacts:
      - app/build/outputs/apk/**/*.apk
      - app/build/outputs/mapping/release/**/mapping.txt
      - app/build/reports/**/*

    publishing:
      email:
        recipients:
          - joepk062@gmail.com

notifications:
  email:
    recipients:
      - joepk062@gmail.com