# Codemagic YAML - Optimized Android Release Pipeline
caches:
  - key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
  - key: android-sdk-34
    paths:
      - $CM_ANDROID_SDK_ROOT/platforms/android-34
      - $CM_ANDROID_SDK_ROOT/build-tools/34.0.0

workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    
    environment:
      groups:
        - android_signing  # Contains FIREBASE_TOKEN and signing keys
      vars:
        BUILD_TYPE: "release"
        FIREBASE_APP_ID: "1:1234567890:android:abcdefghijk"  # Replace with your actual ID
      java: 17

    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Environment Verification
        script: |
          echo "=== Environment Diagnostics ==="
          echo "Java version: $(java -version 2>&1 | head -n 1)"
          echo "Android SDK path: $CM_ANDROID_SDK_ROOT"
          echo "PATH: $PATH"
          ls -la $CM_ANDROID_SDK_ROOT/cmdline-tools/latest/bin

      - name: Build and Verify
        script: |
          ./gradlew clean assemble${BUILD_TYPE} --stacktrace --info
          ./gradlew lintRelease
          
          # APK analysis
          apkanalyzer apk summary app/build/outputs/apk/release/app-release.apk
          apkanalyzer files list app/build/outputs/apk/release/app-release.apk | grep lib/arm64-v8a/

      - name: Security Check
        script: |
          if grep -r "android:debuggable=\"true\"" app/src/main/AndroidManifest.xml; then
            echo "ERROR: Release build must not be debuggable!"
            exit 1
          fi

      - name: Publish to Firebase
        script: |
          # Install Firebase CLI if not present
          if ! command -v firebase &> /dev/null; then
            npm install -g firebase-tools
          fi
          
          firebase appdistribution:distribute \
            app/build/outputs/apk/release/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups "testers" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - app/build/outputs/apk/**/*.apk
      - app/build/outputs/mapping/release/**/mapping.txt
      - app/build/reports/**/*

    publishing:
      email:
        recipients:
          - joepk062@gmail.com

notifications:
  email:
    recipients:
      - joepk062@gmail.com
  slack:
    - channel: '#android-builds'
      notify_on_build_start: true